<?xml version="1.0" encoding="UTF-8">
<xsd:schema xmlns:xsd= "http://www.w3.org/2001/XMLSchema"> 
<xsd:element name="Organization">
  <xsd:complexType>
    <xsd:sequence>
      < name="Department">
         <xsd:complexType>

           <xsd:sequence>
             <xsd:element name="DepartmentID" type="xsd:int"/>
             <xsd:element name="Name" type="String" />
            
             <xsd:element name="Employees">  
               
               <xsd:complexType>
                 <xsd:sequence>
                   <xsd:element name="EmployeeID" type="xsd:int" />
                   <xsd:element name="Name" type="xsd:string" />
                   <xsd:element name="Position" type="xsd:String" />
                   <xsd:element name="Salary" type="xsd:decimal" />
                 </xsd:sequence>
               </xsd:complexType>
               
             </xsd:element>

           </xsd:sequence>

         </xsd:complexType>
     
     
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


</xsd:element>

</xsd:schema>